### ISSUE TITLE
P-DOR takes long time to end

### ISSUE THREAD

**Issue by Ilaria-Pirona** [SteMIDIfactory/P-DOR#6]
Good evening,
I am launching your tool on 44 bacterial genomes that are extremely similar to each other.
The tool failed to finish optimising the phylogenetic tree despite running for more than 48 hours.
Should I change the threshold number of SNPs to define an epidemic cluster? What do you advice to make the program work properly?
Thank you in advance

**Comment by gbatbiff** [comment]
Hi Ilaria,
Usually with that kind of dataset the analysis should be fairly quick, did you also get any errors? The running time of iqtree can depend on several reasons (e.g. cpus, alignment) but is not related to the SNP threshold as the clusters are defined after generating the tree, so I might need some details about your analysis. Could you please copy here the command you used? Also, how long is the alignment (SNP_alignment.core.fasta) you obtained? Thanks

**Comment by Ilaria-Pirona** [comment]
The command I executed is:

python3.8 P-DOR.py -q ../input/ -sd Acinetobacter_baumannii.msh -ref reference/Acinetobacter.fna -snp_thr 20 -t 16 -n 10 -meta metadati_pazienti.csv

The file SNP_alignment.core.fasta has 344 lines ( 6.3M)


This is where it gets stuccked:

--------------------------------------------------------------------
|             INITIALIZING CANDIDATE TREE SET                      |
--------------------------------------------------------------------
Generating 98 parsimony trees... 1206.383 second
Computing log-likelihood of 98 initial trees ... 8252.824 seconds
Current best score: -437351.626

Do NNI search on 20 best initial trees
Optimizing NNI: done in 505.795 secs using 399% CPU
Estimate model parameters (epsilon = 0.100)
BETTER TREE FOUND at iteration 1: -437279.877
Optimizing NNI: done in 1167.11 secs using 395.8% CPU
Estimate model parameters (epsilon = 0.100)
BETTER TREE FOUND at iteration 2: -436109.210
Optimizing NNI: done in 1035.91 secs using 395% CPU
Optimizing NNI: done in 1221.35 secs using 394.3% CPU
Optimizing NNI: done in 970.62 secs using 397.4% CPU
Optimizing NNI: done in 1037.43 secs using 398.9% CPU
Optimizing NNI: done in 1192.29 secs using 396.7% CPU
Optimizing NNI: done in 1264.22 secs using 395.3% CPU
Optimizing NNI: done in 1111.4 secs using 398.1% CPU
Optimizing NNI: done in 1163.36 secs using 397.6% CPU
Iteration 10 / LogL: -436681.322 / Time: 5h:59m:57s
Optimizing NNI: done in 1158.14 secs using 397.5% CPU
Optimizing NNI: done in 1223.38 secs using 399% CPU
Optimizing NNI: done in 1179.55 secs using 397.6% CPU
Optimizing NNI: done in 1155.39 secs using 399.2% CPU
Optimizing NNI: done in 1093.52 secs using 395.9% CPU
Optimizing NNI: done in 1157.68 secs using 396.6% CPU
Optimizing NNI: done in 1199.09 secs using 396.9% CPU
Optimizing NNI: done in 1173.4 secs using 399.1% CPU
Optimizing NNI: done in 1198.41 secs using 404.2% CPU
Optimizing NNI: done in 1211.01 secs using 401.5% CPU
Iteration 20 / LogL: -438227.373 / Time: 9h:15m:49s
Finish initializing candidate tree set (20)
Current best tree score: -436109.210 / CPU time: 32858.522
Number of iterations: 20
--------------------------------------------------------------------
|               OPTIMIZING CANDIDATE TREE SET                      |
--------------------------------------------------------------------
Optimizing NNI: done in 1364.64 secs using 399.2% CPU
Optimizing NNI: done in 1392.48 secs using 396.1% CPU
Optimizing NNI: done in 1639.08 secs using 399.9% CPU
Optimizing NNI: done in 1345.24 secs using 398.6% CPU
Optimizing NNI: done in 1374.89 secs using 396.3% CPU
Optimizing NNI: done in 1426.1 secs using 396.4% CPU
Optimizing NNI: done in 1398.81 secs using 398.7% CPU
Optimizing NNI: done in 1415.17 secs using 396.7% CPU
Optimizing NNI: done in 1517.81 secs using 408% CPU
Optimizing NNI: done in 1210.79 secs using 415.4% CPU
Iteration 30 / LogL: -436181.207 / Time: 13h:10m:38s (32h:42m:58s left)
Optimizing NNI: done in 1181.85 secs using 417.2% CPU

**Comment by gbatbiff** [comment]
This is fine, it seems the issue here is about iq-tree. I assume that you are running it on a server or workstation, have you tried to re-run the analysis using more threads? Or 16 is the maximum you have? About the alignment I mean how many snps you got, you can also check this in SNP_positions.core.list

**Comment by Ilaria-Pirona** [comment]
Good morning,
thank you for your prompt reply and for your interest in my project. Yes
the programme was launched on a virtual machine with 16 cpus, I cannot use
more than that and they are often shared with other processes launched by
other collaborators. I attach to this email the data you have requested
from me, in the hope that you can give me some suggestions as to why I
cannot easily get results.
Thank you in advance for your assistance.
Best regards,
Ilaria

PS: The program as you can see is still running...

Optimizing NNI: done in 1387.43 secs using 396.5% CPU

Iteration 90 / LogL: -436698.369 / Time: 35h:32m:50s (24h:45m:48s left)

Optimizing NNI: done in 1173.45 secs using 398.1% CPU


Il giorno gio 12 dic 2024 alle ore 10:33 Ilaria Pirona <
***@***.***> ha scritto:

**Comment by gbatbiff** [comment]
The long time required by iq-tree here it could either due the amount of RAM or number of threads used simultaneously during other processes that are probably slowing down the analysis. I would suggest you ensure that the RAM is not overflowed and/or that not many processes are running at the same time on the server

**Comment by Ilaria-Pirona** [comment]
Good afternoon,
you were right! I just saw it today, it took a while, I will try to run it
in a more suited machine.
Thanks a lot for the help and have a nice winter holiday.
Best regards,
Ilaria

####################


Analysis completed in 169 hours and 55.557168 minutes

Results are stored in folder
/mnt/disks/phame-acinetobacter/P-DOR/Results_2024-12-10_12-47-57

####################

Il giorno lun 16 dic 2024 alle ore 11:39 Gherard Batisti Biffignandi <
***@***.***> ha scritto:
